### ISSUE TITLE
Please make xnbcli-Linux for other architecture

### ISSUE THREAD

**Issue by LeonovichID** [LeonBlade/xnbcli#29]
I have problem when trying to open xnbcli-linux command in my device.

Im using Termux and installed Ubuntu with armhf.Most android device using Armhf/Arm64.And your file doesnt support the architecture.Please make it for this arch so it Will helpful for android user who doesnt have PC.Thanks.

**Comment by LeonBlade** [comment]
I'm not sure if Node.js supports armhf. If it does though, I can't really build for it myself. If you would like to use xnbcli in this configuration, you can just install Node.js yourself and run the JavaScript manually instead of trying to use a pre-built binary.

1. Install Node.js and NPM.
2. Download the git repository.
3. Run `npm install` in the directory.
4. Run `npm run unpack` to unpack and `npm run pack` to pack files located in the folders.

**Comment by LeonovichID** [comment]
Well,ill try it first...

**Comment by LeonovichID** [comment]
It works fine.Thanks
