### ISSUE TITLE
Can't run pack.command on Mac

### ISSUE THREAD

**Issue by ThatVanessa** [LeonBlade/xnbcli#57]
Whenever I try to run the pack.command file, I get the error "The file "pack.command" could not be executed because you do not have appropriate access privileges." I've tried changing the access privileges and reinstalling the program, but neither one worked.

<img width="621" alt="Screenshot 2024-05-24 at 5 36 17 PM-2" src="https://github.com/LeonBlade/xnbcli/assets/170771371/eb21a044-cb12-4b88-98e6-3bb0d80942b1">

**Comment by LeonBlade** [comment]
I'm terribly sorry for the delay in responding to this. I'm going to respond anyway for the sake of leaving it here for future reference.

If you have an issue with running the command file, you can try to run `chmod +x pack.command` and on the unpack file in order to grand privileges. You may need to run it in an elevated state (`sudo chmod +x pack.command`) and then use your password in order to give the "execution" privilege to the file (that's what the +x means).

Alternatively, if you open the pack and unpack command files in a text editor, you can run whatever commands they have in them manually in the terminal.

Sorry about the late response, and I hope someone can benefit from this.
